name: "Linux build runner image"

env:
    icu_version: "74.2"
    openssl_version: "3.0.14"
    python_version: "3.9.19"
    tcl_version: "8.6.14"

on:
    workflow_dispatch:
        inputs:
    repository_dispatch:
        types:
           - lin_runner

jobs:
    build:
        runs-on: ubuntu-20.04

        strategy:
          fail-fast: false
          matrix:
            release:
              - xenial
              - bionic
            include:
              - release: xenial
                container: ubuntu:xenial
                target_arch: x86_64
                docker_platform: linux/amd64
              - release: bionic
                container: ubuntu:bionic
                target_arch: x86_64
                docker_platform: linux/amd64
        steps:
            - name: Prepare Dockerfile
              run: |
                v=${{ env.icu_version }}
                icu_url="https://github.com/unicode-org/icu/releases/download/release-${v%.*}-${v#*.}/icu4c-${v%.*}_${v#*.}-src.tgz"
                openssl_url="https://www.openssl.org/source/openssl-${{ env.openssl_version }}.tar.gz"
                python_url="https://www.python.org/ftp/python/${{ env.python_version }}/Python-${{ env.python_version }}.tar.xz"
                tcl_url="https://downloads.sourceforge.net/project/tcl/Tcl/${{ env.tcl_version }}/tcl${{ env.tcl_version }}-src.tar.gz"

                tee Dockerfile <<EOF_Dockerfile
                FROM ${{ matrix.container }}
                ENV LD_LIBRARY_PATH=/usr/local/lib
                ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
                ENV TARGET_ARCH=${{ matrix.target_arch }}
                ENV TZ=UTC
                RUN true \
                    && ln -snf /usr/share/zoneinfo/UTC /etc/localtime && echo UTC > /etc/timezone \
                    && yes | { export DEBIAN_FRONTEND=noninteractive; apt-get -y update; apt-get -yqq upgrade; apt-get -yqq dist-upgrade; apt-get -yqq install keyboard-configuration; } \
                    && apt-get -y install sudo build-essential curl g++ git pkg-config unzip wget xz-utils zstd \
                    && echo 'ALL ALL = (ALL) NOPASSWD: ALL' >>/etc/sudoers
                RUN curl -L $icu_url | tar -xz \
                    && cd icu/source && ./configure --prefix=/usr/local --enable-rpath \
                    && make -j$(nproc) && make install \
                    && cd ../.. && rm -fr icu
                RUN curl -L $openssl_url | tar -xz \
                    && cd openssl-${{ env.openssl_version }} && ./config --prefix=/usr/local --openssldir=/usr/local/ssl --libdir=lib \
                    && make -j$(nproc) && make install \
                    && cd ../.. && rm -fr openssl-${{ env.openssl_version }}
                # Installing Python under /usr improves our chances to match user's installed Python
                # On Bionic, install system python3 first so it is not reinstalled by aqtinstall later
                RUN curl -L $python_url | xz -dc | tar -x \
                    && apt-get -y install libbz2-dev libffi-dev libgdbm-dev liblzma-dev libsqlite3-dev uuid-dev zlib1g-dev \
                    && case ${{ matrix.release }} in xenial*) ;; *) apt-get -y install libgdbm-compat-dev ;; esac \
                    && case ${{ matrix.release }} in bionic*) apt-get -y install python3 python3-distutils python3-lib2to3 python3-minimal ;; esac \
                    && cd Python-${{ env.python_version }} && ./configure --prefix=/usr --with-openssl=/usr/local --enable-optimizations --enable-shared --without-static-libpython \
                    && make -j$(nproc) && make install \
                    && ln -fns python${python_version%.*} /usr/bin/python3 \
                    && cd ../../ && rm -fr Python-${{ env.python_version }} \
                    && case ${{ matrix.release }} in xenial*) ;; *) apt-get -y remove libgdbm-compat-dev ;; esac \
                    && apt-get -y remove libbz2-dev libffi-dev libgdbm-dev liblzma-dev libsqlite3-dev uuid-dev zlib1g-dev
                RUN curl -L $tcl_url | tar -xz \
                    && cd tcl${{ env.tcl_version }}/unix && ./configure --prefix=/usr/local \
                    && make -j$(nproc) && make install \
                    && ln -sf tclsh${tcl_version%.*} /usr/local/bin/tclsh \
                    && cd ../.. && rm -fr tcl${{ env.tcl_version }}
                # Install Qt runtime deps here
                RUN apt-get -y install \
                    libgl1-mesa-dev \
                    libwayland-client0 libwayland-cursor0 \
                    libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 \
                    libxcb-render-util0 libxcb-xinerama0 libxcb-xkb1 \
                    libxkbcommon0 libxkbcommon-x11-0
                EOF_Dockerfile

            - name: Build and publish
              uses: VaultVulp/gp-docker-action@1.6.0
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
                image-name: gha-build-runner-${{ matrix.release }} # Provide Docker image name
                image-tag: latest
                custom-args: --platform=${{ matrix.docker_platform }}
